name: "godot-ci export"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GODOT_VERSION: 4.3.stable
  EXPORT_NAME: minijam-168
  ITCH_GAME: minijam-168
  ITCH_USER: erebrus

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
        ls ~/.local/share/godot/export_templates/${GODOT_VERSION}
    - name: Web Build
      run: |
        mkdir -v -p build/html
        cd godot
        godot -v --headless --export-release "Web" ../build/html/index.html
        godot -v --headless --export-release "Web" ../build/html/index.html
    - name: Publish to Itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        PACKAGE: godot/build/html
  
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
          ls ~/.local/share/godot/export_templates/${GODOT_VERSION}
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd godot
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
          godot -v --headless --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Publish to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          PACKAGE: godot/build/windows
